// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using Invert.ECS;


public class LevelEventDataBase : object {
    
    private Int32 _LevelId;
    
    public Int32 LevelId {
        get {
            return _LevelId;
        }
        set {
            _LevelId = value;
        }
    }
}

public class EnterLevelEventDataBase : object {
}
