// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace FlipCube {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.Kernel;
    using UniRx;
    
    
    public partial class AnimatedWidgetGroup : ReactiveGroup<AnimatedWidget> {
        
        private IEcsComponentManagerOf<Animated> _AnimatedManager;
        
        private IEcsComponentManagerOf<UIWidget> _UIWidgetManager;
        
        private int lastEntityId;
        
        private Animated Animated;
        
        private UIWidget UIWidget;
        
        public IEcsComponentManagerOf<Animated> AnimatedManager {
            get {
                return _AnimatedManager;
            }
            set {
                _AnimatedManager = value;
            }
        }
        
        public IEcsComponentManagerOf<UIWidget> UIWidgetManager {
            get {
                return _UIWidgetManager;
            }
            set {
                _UIWidgetManager = value;
            }
        }
        
        public override System.Collections.Generic.IEnumerable<UniRx.IObservable<int>> Install(uFrame.ECS.IComponentSystem componentSystem) {
            AnimatedManager = componentSystem.RegisterComponent<Animated>();
            yield return AnimatedManager.CreatedObservable.Select(_=>_.EntityId);;
            yield return AnimatedManager.RemovedObservable.Select(_=>_.EntityId);;
            UIWidgetManager = componentSystem.RegisterComponent<UIWidget>();
            yield return UIWidgetManager.CreatedObservable.Select(_=>_.EntityId);;
            yield return UIWidgetManager.RemovedObservable.Select(_=>_.EntityId);;
        }
        
        public override bool Match(int entityId) {
            lastEntityId = entityId;
            if ((Animated = AnimatedManager[entityId]) == null) {
                return false;
            }
            if ((UIWidget = UIWidgetManager[entityId]) == null) {
                return false;
            }
            return true;
        }
        
        public override AnimatedWidget Select() {
            var item = new AnimatedWidget();;
            item.EntityId = lastEntityId;
            item.Animated = Animated;
            item.UIWidget = UIWidget;
            return item;
        }
    }
}
