// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace FlipCube {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.Kernel;
    using UniRx;
    
    
    public partial class GameDependencySceneDataGroup : ReactiveGroup<GameDependencySceneData> {
        
        private IEcsComponentManagerOf<SceneData> _SceneDataManager;
        
        private IEcsComponentManagerOf<GameDependency> _GameDependencyManager;
        
        private int lastEntityId;
        
        private SceneData SceneData;
        
        private GameDependency GameDependency;
        
        public IEcsComponentManagerOf<SceneData> SceneDataManager {
            get {
                return _SceneDataManager;
            }
            set {
                _SceneDataManager = value;
            }
        }
        
        public IEcsComponentManagerOf<GameDependency> GameDependencyManager {
            get {
                return _GameDependencyManager;
            }
            set {
                _GameDependencyManager = value;
            }
        }
        
        public override System.Collections.Generic.IEnumerable<UniRx.IObservable<int>> Install(uFrame.ECS.IComponentSystem componentSystem) {
            SceneDataManager = componentSystem.RegisterComponent<SceneData>();
            yield return SceneDataManager.CreatedObservable.Select(_=>_.EntityId);;
            yield return SceneDataManager.RemovedObservable.Select(_=>_.EntityId);;
            GameDependencyManager = componentSystem.RegisterComponent<GameDependency>();
            yield return GameDependencyManager.CreatedObservable.Select(_=>_.EntityId);;
            yield return GameDependencyManager.RemovedObservable.Select(_=>_.EntityId);;
        }
        
        public override bool Match(int entityId) {
            lastEntityId = entityId;
            if ((SceneData = SceneDataManager[entityId]) == null) {
                return false;
            }
            if ((GameDependency = GameDependencyManager[entityId]) == null) {
                return false;
            }
            return true;
        }
        
        public override GameDependencySceneData Select() {
            var item = new GameDependencySceneData();;
            item.EntityId = lastEntityId;
            item.SceneData = SceneData;
            item.GameDependency = GameDependency;
            return item;
        }
    }
}
