// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace FlipCube {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.Kernel;
    using UniRx;
    
    
    [uFrame.Attributes.ComponentId(11)]
    public partial class LevelSelectionWidget : uFrame.ECS.GroupItem {
        
        private LevelSelectionUI _LevelSelectionUI;
        
        private UIWidget _UIWidget;
        
        private Composite _Composite;
        
        public LevelSelectionUI LevelSelectionUI {
            get {
                return _LevelSelectionUI;
            }
            set {
                _LevelSelectionUI = value;
            }
        }
        
        public UIWidget UIWidget {
            get {
                return _UIWidget;
            }
            set {
                _UIWidget = value;
            }
        }
        
        public Composite Composite {
            get {
                return _Composite;
            }
            set {
                _Composite = value;
            }
        }
        
        public override int ComponentId {
            get {
                return 11;
            }
        }
    }
}
