// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace FlipCube {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.Kernel;
    using UniRx;
    
    
    [uFrame.Attributes.ComponentId(14)]
    public partial class LoadingScreenWidget : uFrame.ECS.GroupItem {
        
        private LoadingScreenUI _LoadingScreenUI;
        
        private UIWidget _UIWidget;
        
        public LoadingScreenUI LoadingScreenUI {
            get {
                return _LoadingScreenUI;
            }
            set {
                _LoadingScreenUI = value;
            }
        }
        
        public UIWidget UIWidget {
            get {
                return _UIWidget;
            }
            set {
                _UIWidget = value;
            }
        }
        
        public override int ComponentId {
            get {
                return 14;
            }
        }
    }
}
