// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using Invert.ECS;


public class SimpleGameMenuItems : object {
    
    [UnityEditor.MenuItem("Assets/Create/SimpleGame/Player", false)]
    public static void CreatePlayer() {
        uFrameMenu.CreateAsset<PlayerEntity>();
    }
}
