// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using Invert.ECS;


public enum CubeSystemEvents {
    
    RollBegin,
    
    RollComplete,
    
    Reset,
    
    MoveTo,
    
    SplitCube,
    
    CubeMoved,
}

public enum CubeInputSystemEvents {
    
    Selected,
    
    L,
    
    F,
    
    R,
    
    B,
}

public enum RollerState {
    
    StandingUp,
    
    LayingAcross,
    
    LayingForward,
}

public enum CubeGravitySystemEvents {
    
    OnFall,
    
    RollCompletedStandingUp,
    
    RolledNextToCube,
}

public enum CubeMoveDirection {
    
    Left,
    
    Right,
    
    Forward,
    
    Backwards,
}

public enum CameraSystemEvents {
}

public enum PlateSystemEvents {
    
    CubeEntered,
    
    CubeLeft,
    
    GoalPlateHit,
    
    SwitchPlateHit,
    
    CubeEnteredStandingUp,
}

public enum TeliporterSystemEvents {
    
    Teliporting,
}

public enum SwitchPlateSystemEvents {
    
    PlateActivatedOn,
    
    PlateActivatedOff,
}

public enum SwitchPlatePivot {
    
    Bottom,
    
    Top,
    
    Left,
    
    Right,
}

public enum ShiftingPlateEvents {
}

public enum GoalPlateSystemEvents {
}

public enum DissolvePlateSystemEvents {
}

public enum PlateRegister {
    
    A,
    
    B,
    
    C,
    
    D,
    
    E,
    
    F,
    
    G,
    
    H,
    
    I,
    
    J,
}

public enum LevelSystemEvents {
    
    LevelComplete,
    
    LevelQuit,
    
    LevelRestart,
    
    EnterLevel,
    
    EnteredLevel,
}

public enum FlipCubeGameSystemEvents {
    
    GameOver,
}

public enum FlipCubeNotificationsEvents {
}

public enum FlipCubeSystemEvents {
    
    GameReady,
    
    ResetGame,
    
    NextLevel,
    
    BackToZone,
    
    GameDataReady,
}

public enum BasicGameSystemEvents {
}

public enum LevelProgressStatus {
    
    Perfect,
    
    Good,
    
    Bad,
    
    Fair,
}

public enum SpecialFXSystemEvents {
}

public enum FlipCubeSoundSystemEvents {
}

public enum NotificationSystemEvents {
    
    Display,
}

public enum XPSystemEvents {
}

public enum PlayerSystemEvents {
    
    PlayerLoaded,
    
    AddXp,
    
    PlayerXpChanged,
}

public enum ScoringSystemEvents {
    
    AddToScore,
    
    RemoveFromScore,
}

public enum ZoneSystemEvents {
    
    EnterZone,
    
    EnteredZone,
}

public enum PlayerDataSystemEvents {
    
    SaveGame,
    
    PlayerLoggedIn,
    
    PlayerLoggedOut,
    
    LoadGame,
    
    LoginPlayer,
    
    SetPlayerStat,
    
    IncrementPlayerStat,
    
    DecrementPlayerStat,
    
    LogoutPlayer,
    
    StatChanged,
    
    OnSaveComponent,
}

public enum FlipCubeUISystemEvents {
}

public enum HUDSystemEvents {
}

public enum WindowSystemEvents {
    
    ShowWindow,
    
    CloseWindow,
    
    ToggleWindow,
}

public enum FlipCubeWindow {
    
    Zones,
    
    Friends,
    
    Profile,
    
    Messages,
    
    LeaderBoard,
    
    LevelComplete,
}

public enum ZonesWindowSystemEvents {
}

public enum FriendsWindowSystemEvents {
}

public enum ProfileWindowSystemEvents {
}

public enum AccountWindowSystemEvents {
}

public enum TutorialSystemEvents {
}
