// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using Invert.ECS;
using UnityEngine;


public class RollableBase : Invert.ECS.Unity.UnityComponent {
    
    [UnityEngine.SerializeField()]
    private Single _RollSpeed;
    
    [UnityEngine.SerializeField()]
    private RollerState _RestState;
    
    [UnityEngine.SerializeField()]
    private Boolean _IsRolling;
    
    [UnityEngine.SerializeField()]
    private Int32 _Length;
    
    [UnityEngine.SerializeField()]
    private Vector3 _StartingPosition;
    
    [UnityEngine.SerializeField()]
    private Boolean _IsSplit;
    
    public virtual Single RollSpeed {
        get {
            return _RollSpeed;
        }
        set {
            _RollSpeed = value;
        }
    }
    
    public virtual RollerState RestState {
        get {
            return _RestState;
        }
        set {
            _RestState = value;
        }
    }
    
    public virtual Boolean IsRolling {
        get {
            return _IsRolling;
        }
        set {
            _IsRolling = value;
        }
    }
    
    public virtual Int32 Length {
        get {
            return _Length;
        }
        set {
            _Length = value;
        }
    }
    
    public virtual Vector3 StartingPosition {
        get {
            return _StartingPosition;
        }
        set {
            _StartingPosition = value;
        }
    }
    
    public virtual Boolean IsSplit {
        get {
            return _IsSplit;
        }
        set {
            _IsSplit = value;
        }
    }
}

[UnityEngine.AddComponentMenu("FlipCube/Rollable")]
public partial class Rollable {
}

public class CubeBase : Invert.ECS.Unity.UnityComponent {
    
    [UnityEngine.SerializeField()]
    private Boolean _IsSelected;
    
    public virtual Boolean IsSelected {
        get {
            return _IsSelected;
        }
        set {
            _IsSelected = value;
        }
    }
}

[UnityEngine.AddComponentMenu("FlipCube/Cube")]
public partial class Cube {
}

public class MoveDirectionOnEnterBase : Invert.ECS.Unity.UnityComponent {
    
    [UnityEngine.SerializeField()]
    private Int32 _RollableId;
    
    [UnityEngine.SerializeField()]
    private CubeMoveDirection _MoveDirection;
    
    public virtual Int32 RollableId {
        get {
            return _RollableId;
        }
        set {
            _RollableId = value;
        }
    }
    
    public virtual CubeMoveDirection MoveDirection {
        get {
            return _MoveDirection;
        }
        set {
            _MoveDirection = value;
        }
    }
}

[UnityEngine.AddComponentMenu("FlipCube/MoveDirectionOnEnter")]
public partial class MoveDirectionOnEnter {
}

public class NotifyOnEnterBase : Invert.ECS.Unity.UnityComponent {
    
    [UnityEngine.SerializeField()]
    private String _Message;
    
    public virtual String Message {
        get {
            return _Message;
        }
        set {
            _Message = value;
        }
    }
}

[UnityEngine.AddComponentMenu("FlipCube/NotifyOnEnter")]
public partial class NotifyOnEnter {
}

public class BasicGameBase : Invert.ECS.Unity.UnityComponent {
}

[UnityEngine.AddComponentMenu("FlipCube/BasicGame")]
public partial class BasicGame {
}

public class EnterLevelOnEnterBase : Invert.ECS.Unity.UnityComponent {
    
    [UnityEngine.SerializeField()]
    private Int32 _LevelId;
    
    public virtual Int32 LevelId {
        get {
            return _LevelId;
        }
        set {
            _LevelId = value;
        }
    }
}

[UnityEngine.AddComponentMenu("FlipCube/EnterLevelOnEnter")]
public partial class EnterLevelOnEnter {
}

public class CubeSpawnPointBase : Invert.ECS.Unity.UnityComponent {
}

[UnityEngine.AddComponentMenu("FlipCube/CubeSpawnPoint")]
public partial class CubeSpawnPoint {
}

public class SwitchOnWithXpBase : Invert.ECS.Unity.UnityComponent {
    
    [UnityEngine.SerializeField()]
    private Int32 _RequiredXp;
    
    public virtual Int32 RequiredXp {
        get {
            return _RequiredXp;
        }
        set {
            _RequiredXp = value;
        }
    }
}

[UnityEngine.AddComponentMenu("FlipCube/SwitchOnWithXp")]
public partial class SwitchOnWithXp {
}

public class BackgroundSceneBase : Invert.ECS.Unity.UnityComponent {
}

[UnityEngine.AddComponentMenu("FlipCube/BackgroundScene")]
public partial class BackgroundScene {
}
