// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace FlipCube {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using UnityEngine;
    using uFrame.Kernel;
    
    
    public class LoginUISystemUserLoggedInHandler {
        
        private FlipCube.UserLoggedIn _Event;
        
        private uFrame.ECS.EcsSystem _System;
        
        private FlipCube.LoginLoadingUI LoopGroupNode9_Item = default( FlipCube.LoginLoadingUI );
        
        private UnityEngine.GameObject ActionNode6_gameObject = default( UnityEngine.GameObject );
        
        private UnityEngine.MonoBehaviour ActionNode6_behaviour = default( UnityEngine.MonoBehaviour );
        
        public FlipCube.UserLoggedIn Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual void Execute() {
            // LoopGroupNode
            var LoopGroupNode9_GroupComponents = System.ComponentSystem.RegisterComponent<FlipCube.LoginLoadingUI>().Components;
            for (var LoopGroupNode9_ItemIndex = 0
            ; LoopGroupNode9_ItemIndex < LoopGroupNode9_GroupComponents.Count; LoopGroupNode9_ItemIndex++
            ) {
                LoopGroupNode9_Item = LoopGroupNode9_GroupComponents[LoopGroupNode9_ItemIndex];
                LoopGroupNode9_Next();
            }
        }
        
        private void LoopGroupNode9_Next() {
            ActionNode6_behaviour = LoopGroupNode9_Item;
            // ActionNode
            // Visit uFrame.Actions.GameObjects.DeactiateGameObject
            uFrame.Actions.GameObjects.DeactiateGameObject(ActionNode6_gameObject, ActionNode6_behaviour);
        }
    }
}
