// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace FlipCube {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.Kernel;
    using UnityEngine;
    
    
    public class LoginUISystemUserLoggedInHandler {
        
        private FlipCube.UserLoggedIn _Event;
        
        private uFrame.ECS.EcsSystem _System;
        
        private FlipCube.LoginLoadingUI LoopGroupNode9_Item = default( FlipCube.LoginLoadingUI );
        
        private UnityEngine.GameObject ActionNode6_gameObject = default( UnityEngine.GameObject );
        
        private UnityEngine.MonoBehaviour ActionNode6_behaviour = default( UnityEngine.MonoBehaviour );
        
        public FlipCube.UserLoggedIn Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual System.Collections.IEnumerator Execute() {
            // LoopGroupNode
            while (this.DebugInfo("0057f1bd-681a-42f7-9e54-a120a2924893","fe471139-5cf6-4036-9684-5ac1953d460b", this) == 1) yield return null;
            var LoopGroupNode9_GroupComponents = System.ComponentSystem.RegisterComponent<FlipCube.LoginLoadingUI>().Components;
            for (var LoopGroupNode9_ItemIndex = 0
            ; LoopGroupNode9_ItemIndex < LoopGroupNode9_GroupComponents.Count; LoopGroupNode9_ItemIndex++
            ) {
                LoopGroupNode9_Item = LoopGroupNode9_GroupComponents[LoopGroupNode9_ItemIndex];
                System.StartCoroutine(LoopGroupNode9_Next());
            }
            yield break;
        }
        
        private System.Collections.IEnumerator LoopGroupNode9_Next() {
            ActionNode6_behaviour = LoopGroupNode9_Item;
            // ActionNode
            while (this.DebugInfo("fe471139-5cf6-4036-9684-5ac1953d460b","eed8b3f0-85d4-49be-ac66-f9909f789645", this) == 1) yield return null;
            // Visit uFrame.Actions.GameObjects.DeactiateGameObject
            uFrame.Actions.GameObjects.DeactiateGameObject(ActionNode6_gameObject, ActionNode6_behaviour);
            yield break;
        }
    }
}
