// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace FlipCube {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.Kernel;
    using UnityEngine;
    
    
    public class LoginSystemUserLoggedInHandler {
        
        private FlipCube.UserLoggedIn _Event;
        
        private uFrame.ECS.EcsSystem _System;
        
        private bool Yes = true;
        
        private FlipCube.LoadData PublishEventNode5_Result = default( FlipCube.LoadData );
        
        public FlipCube.UserLoggedIn Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual System.Collections.IEnumerator Execute() {
            // SetVariableNode
            while (this.DebugInfo("31600f72-c34b-4a8e-b5e3-8ebfb0a370c5","3acd4794-2a34-4e8e-914a-327acab7664a", this) == 1) yield return null;
            System.BlackBoardSystem.Get<UserLoginInfo>().IsLoggedIn = (System.Boolean)Yes;
            // PublishEventNode
            while (this.DebugInfo("3acd4794-2a34-4e8e-914a-327acab7664a","5bdadfd1-49f1-4b69-a7be-3ea1626e9ffe", this) == 1) yield return null;
            var PublishEventNode5_Event = new LoadData();
            System.Publish(PublishEventNode5_Event);
            PublishEventNode5_Result = PublishEventNode5_Event;
            yield break;
        }
    }
}
