// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace FlipCube {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using UnityEngine;
    using uFrame.Kernel;
    
    
    public class LoginSystemUserLoggedOutHandler {
        
        private FlipCube.UserLoggedOut _Event;
        
        private uFrame.ECS.EcsSystem _System;
        
        private bool Yes = false;
        
        public FlipCube.UserLoggedOut Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual System.Collections.IEnumerator Execute() {
            // SetVariableNode
            while (this.DebugInfo("f6399b8b-7316-403d-a45d-7cdfced45c42","8b014875-05d2-4e5e-9977-dc2faa26803d", this) == 1) yield return null;
            System.BlackBoardSystem.Get<UserLoginInfo>().IsLoggedIn = (System.Boolean)Yes;
            yield break;
        }
    }
}
