// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Invert.ECS.Graphs {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using Invert.Core.GraphDesigner;
    
    
    public class SystemsNodeDrawerBase : GenericNodeDrawer<SystemsNode,SystemsNodeViewModel> {
        
        public SystemsNodeDrawerBase(SystemsNodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
    
    public class SystemNodeDrawerBase : GenericNodeDrawer<SystemNode,SystemNodeViewModel> {
        
        public SystemNodeDrawerBase(SystemNodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
    
    public class ComponentNodeDrawerBase : GenericNodeDrawer<ComponentNode,ComponentNodeViewModel> {
        
        public ComponentNodeDrawerBase(ComponentNodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
    
    public class EventNodeDrawerBase : GenericNodeDrawer<EventNode,EventNodeViewModel> {
        
        public EventNodeDrawerBase(EventNodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
    
    public class EventHandlerNodeDrawerBase : GenericNodeDrawer<EventHandlerNode,EventHandlerNodeViewModel> {
        
        public EventHandlerNodeDrawerBase(EventHandlerNodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
    
    public class ActionNodeDrawerBase : GenericNodeDrawer<ActionNode,ActionNodeViewModel> {
        
        public ActionNodeDrawerBase(ActionNodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
    
    public class SimpleClassNodeDrawerBase : GenericNodeDrawer<SimpleClassNode,SimpleClassNodeViewModel> {
        
        public SimpleClassNodeDrawerBase(SimpleClassNodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
    
    public class SendSignalNodeDrawerBase : GenericNodeDrawer<SendSignalNode,SendSignalNodeViewModel> {
        
        public SendSignalNodeDrawerBase(SendSignalNodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
    
    public class ConditionNodeDrawerBase : GenericNodeDrawer<ConditionNode,ConditionNodeViewModel> {
        
        public ConditionNodeDrawerBase(ConditionNodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
}
