// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using Invert.ECS;
using UnityEngine;


public class PlateBase : Invert.ECS.Unity.UnityComponent {
}

[UnityEngine.AddComponentMenu("Plates/Plate")]
public partial class Plate {
}

public class TeliporterBase : Invert.ECS.Unity.UnityComponent {
    
    [UnityEngine.SerializeField()]
    private PlateRegister _Register;
    
    public virtual PlateRegister Register {
        get {
            return _Register;
        }
        set {
            _Register = value;
        }
    }
}

[UnityEngine.AddComponentMenu("Plates/Teliporter")]
public partial class Teliporter {
}

public class TeliportableBase : Invert.ECS.Unity.UnityComponent {
}

[UnityEngine.AddComponentMenu("Plates/Teliportable")]
public partial class Teliportable {
}

public class TeliporterTargetBase : Invert.ECS.Unity.UnityComponent {
    
    [UnityEngine.SerializeField()]
    private PlateRegister _Register;
    
    public virtual PlateRegister Register {
        get {
            return _Register;
        }
        set {
            _Register = value;
        }
    }
}

[UnityEngine.AddComponentMenu("Plates/TeliporterTarget")]
public partial class TeliporterTarget {
}

public class GoalPlateBase : Invert.ECS.Unity.UnityComponent {
}

[UnityEngine.AddComponentMenu("Plates/GoalPlate")]
public partial class GoalPlate {
}

public class SwitchPlateTriggerBase : Invert.ECS.Unity.UnityComponent {
    
    [UnityEngine.SerializeField()]
    private PlateRegister _Register;
    
    public virtual PlateRegister Register {
        get {
            return _Register;
        }
        set {
            _Register = value;
        }
    }
}

[UnityEngine.AddComponentMenu("Plates/SwitchPlateTrigger")]
public partial class SwitchPlateTrigger {
}

public class TurnGravityOnEnterBase : Invert.ECS.Unity.UnityComponent {
}

[UnityEngine.AddComponentMenu("Plates/TurnGravityOnEnter")]
public partial class TurnGravityOnEnter {
}

public class DisableColliderOnCollisionBase : Invert.ECS.Unity.UnityComponent {
}

[UnityEngine.AddComponentMenu("Plates/DisableColliderOnCollision")]
public partial class DisableColliderOnCollision {
}

public class SwitchPlateTargetBase : Invert.ECS.Unity.UnityComponent {
    
    [UnityEngine.SerializeField()]
    private SwitchPlatePivot _PivotPoint;
    
    [UnityEngine.SerializeField()]
    private Boolean _On;
    
    [UnityEngine.SerializeField()]
    private Boolean _StartOn;
    
    [UnityEngine.SerializeField()]
    private PlateRegister _Register;
    
    public virtual SwitchPlatePivot PivotPoint {
        get {
            return _PivotPoint;
        }
        set {
            _PivotPoint = value;
        }
    }
    
    public virtual Boolean On {
        get {
            return _On;
        }
        set {
            _On = value;
        }
    }
    
    public virtual Boolean StartOn {
        get {
            return _StartOn;
        }
        set {
            _StartOn = value;
        }
    }
    
    public virtual PlateRegister Register {
        get {
            return _Register;
        }
        set {
            _Register = value;
        }
    }
}

[UnityEngine.AddComponentMenu("Plates/SwitchPlateTarget")]
public partial class SwitchPlateTarget {
}

public class MoveLeftOnLeaveBase : Invert.ECS.Unity.UnityComponent {
    
    [UnityEngine.SerializeField()]
    private Vector3 _Offset;
    
    public virtual Vector3 Offset {
        get {
            return _Offset;
        }
        set {
            _Offset = value;
        }
    }
}

[UnityEngine.AddComponentMenu("Plates/MoveLeftOnLeave")]
public partial class MoveLeftOnLeave {
}

public class TransporterPlateBase : Invert.ECS.Unity.UnityComponent {
    
    [UnityEngine.SerializeField()]
    private Vector3 _MoveOffset;
    
    [UnityEngine.SerializeField()]
    private Boolean _IsOn;
    
    public virtual Vector3 MoveOffset {
        get {
            return _MoveOffset;
        }
        set {
            _MoveOffset = value;
        }
    }
    
    public virtual Boolean IsOn {
        get {
            return _IsOn;
        }
        set {
            _IsOn = value;
        }
    }
}

[UnityEngine.AddComponentMenu("Plates/TransporterPlate")]
public partial class TransporterPlate {
}

public class DissolvePlateBase : Invert.ECS.Unity.UnityComponent {
    
    [UnityEngine.SerializeField()]
    private Boolean _IsDissolved;
    
    public virtual Boolean IsDissolved {
        get {
            return _IsDissolved;
        }
        set {
            _IsDissolved = value;
        }
    }
}

[UnityEngine.AddComponentMenu("Plates/DissolvePlate")]
public partial class DissolvePlate {
}

public class YingYangPlateBase : Invert.ECS.Unity.UnityComponent {
    
    [UnityEngine.SerializeField()]
    private List<Int32> _TargetPlates;
    
    public virtual List<Int32> TargetPlates {
        get {
            return _TargetPlates;
        }
        set {
            _TargetPlates = value;
        }
    }
}

[UnityEngine.AddComponentMenu("Plates/YingYangPlate")]
public partial class YingYangPlate {
}
