// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace FlipCube {
    using FlipCube;
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.Kernel;
    using UniRx;
    using UnityEngine;
    
    
    public partial class FlipCubeAudioSystemBase : uFrame.ECS.EcsSystem {
        
        private IEcsComponentManagerOf<UIWidget> _UIWidgetManager;
        
        public IEcsComponentManagerOf<UIWidget> UIWidgetManager {
            get {
                return _UIWidgetManager;
            }
            set {
                _UIWidgetManager = value;
            }
        }
        
        public override void Setup() {
            base.Setup();
            UIWidgetManager = ComponentSystem.RegisterComponent<UIWidget>(57);
            this.PropertyChangedEvent<UIWidget,FlipCube.WidgetState>(Group=>Group.StateObservable, NewPropertyChangedNodeFilter, null, false);
        }
        
        protected virtual void NewPropertyChangedNode(UIWidget data, UIWidget group, PropertyChangedEvent<FlipCube.WidgetState> value) {
        }
        
        protected void NewPropertyChangedNodeFilter(UIWidget data, PropertyChangedEvent<FlipCube.WidgetState> value) {
            var GroupUIWidget = UIWidgetManager[data.EntityId];
            if (GroupUIWidget == null) {
                return;
            }
            if (!GroupUIWidget.Enabled) {
                return;
            }
            this.NewPropertyChangedNode(data, GroupUIWidget, value);
        }
    }
    
    [uFrame.Attributes.uFrameIdentifier("ec408320-1f2d-4604-9020-86693987bb20")]
    public partial class FlipCubeAudioSystem : FlipCubeAudioSystemBase {
        
        private static FlipCubeAudioSystem _Instance;
        
        [UnityEngine.SerializeField()]
        private AudioClip _WidgetOpen2Clip;
        
        [UnityEngine.SerializeField()]
        private AudioClip _WidgetClose2Clip;
        
        [UnityEngine.SerializeField()]
        private AudioClip _WidgetOpen3Clip;
        
        [UnityEngine.SerializeField()]
        private AudioClip _WidgetClose1Clip;
        
        [UnityEngine.SerializeField()]
        private AudioClip _WidgetOpen1Clip;
        
        [UnityEngine.SerializeField()]
        private AudioClip _WIdgetClose3Clip;
        
        public FlipCubeAudioSystem() {
            Instance = this;
        }
        
        public static FlipCubeAudioSystem Instance {
            get {
                return _Instance;
            }
            set {
                _Instance = value;
            }
        }
        
        public AudioClip WidgetOpen2Clip {
            get {
                return _WidgetOpen2Clip;
            }
            set {
                _WidgetOpen2Clip = value;
            }
        }
        
        public AudioClip WidgetClose2Clip {
            get {
                return _WidgetClose2Clip;
            }
            set {
                _WidgetClose2Clip = value;
            }
        }
        
        public AudioClip WidgetOpen3Clip {
            get {
                return _WidgetOpen3Clip;
            }
            set {
                _WidgetOpen3Clip = value;
            }
        }
        
        public AudioClip WidgetClose1Clip {
            get {
                return _WidgetClose1Clip;
            }
            set {
                _WidgetClose1Clip = value;
            }
        }
        
        public AudioClip WidgetOpen1Clip {
            get {
                return _WidgetOpen1Clip;
            }
            set {
                _WidgetOpen1Clip = value;
            }
        }
        
        public AudioClip WIdgetClose3Clip {
            get {
                return _WIdgetClose3Clip;
            }
            set {
                _WIdgetClose3Clip = value;
            }
        }
    }
}
