// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace FlipCube {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.Kernel;
    using UniRx;
    using UnityEngine;
    
    
    public partial class GameAudioSystemBase : uFrame.ECS.EcsSystem {
        
        public override void Setup() {
            base.Setup();
            this.OnEvent<FlipCube.PlayAudioFX>().Subscribe(_=>{ GameAudioSystemPlayAudioFXFilter(_); }).DisposeWith(this);
        }
        
        protected virtual void GameAudioSystemPlayAudioFXHandler(FlipCube.PlayAudioFX data) {
            var handler = new GameAudioSystemPlayAudioFXHandler();
            handler.System = this;
            handler.Event = data;
            handler.Execute();
        }
        
        protected void GameAudioSystemPlayAudioFXFilter(FlipCube.PlayAudioFX data) {
            this.GameAudioSystemPlayAudioFXHandler(data);
        }
    }
    
    [uFrame.Attributes.uFrameIdentifier("469dc500-4de8-4ab5-a72d-cc037ee627d5")]
    public partial class GameAudioSystem : GameAudioSystemBase {
        
        private static GameAudioSystem _Instance;
        
        [UnityEngine.SerializeField()]
        private AudioSource _AudioFXSource;
        
        [UnityEngine.SerializeField()]
        private AudioSource _MusicSource;
        
        public GameAudioSystem() {
            Instance = this;
        }
        
        public static GameAudioSystem Instance {
            get {
                return _Instance;
            }
            set {
                _Instance = value;
            }
        }
        
        public AudioSource AudioFXSource {
            get {
                return _AudioFXSource;
            }
            set {
                _AudioFXSource = value;
            }
        }
        
        public AudioSource MusicSource {
            get {
                return _MusicSource;
            }
            set {
                _MusicSource = value;
            }
        }
    }
}
