// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace FlipCube {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.Kernel;
    using FlipCube;
    using UnityEngine.UI;
    using UniRx;
    
    
    public partial class LevelSelectionUISystemBase : uFrame.ECS.EcsSystem {
        
        private IEcsComponentManagerOf<LevelSelectionUI> _LevelSelectionUIManager;
        
        private IEcsComponentManagerOf<LevelSelectionUIItem> _LevelSelectionUIItemManager;
        
        public IEcsComponentManagerOf<LevelSelectionUI> LevelSelectionUIManager {
            get {
                return _LevelSelectionUIManager;
            }
            set {
                _LevelSelectionUIManager = value;
            }
        }
        
        public IEcsComponentManagerOf<LevelSelectionUIItem> LevelSelectionUIItemManager {
            get {
                return _LevelSelectionUIItemManager;
            }
            set {
                _LevelSelectionUIItemManager = value;
            }
        }
        
        public override void Setup() {
            base.Setup();
            LevelSelectionUIManager = ComponentSystem.RegisterComponent<LevelSelectionUI>(44);
            LevelSelectionUIItemManager = ComponentSystem.RegisterComponent<LevelSelectionUIItem>(45);
            this.OnEvent<FlipCube.LevelSelectionUIShown>().Subscribe(_=>{ OnLevelSelectionUIShownFilter(_); }).DisposeWith(this);
            this.PropertyChangedEvent<LevelSelectionUI,System.Int32>(Group=>Group.SkipObservable, SkipChangedFilter, Group=>Group.Skip, false);
            this.OnEvent<FlipCube.LevelSelectionUIHiding>().Subscribe(_=>{ OnLevelSelectionUIHidingFilter(_); }).DisposeWith(this);
            this.PropertyChangedEvent<LevelSelectionUIItem,System.Int32>(Group=>Group.LevelIndexObservable, LevelIndexChangedFilter, Group=>Group.LevelIndex, false);
            this.PropertyChangedEvent<LevelSelectionUI,System.Boolean>(Group=>Group.HiddenObservable, HiddenChangedFilter, Group=>Group.Hidden, false);
            this.OnEvent<FlipCube.LevelSelectionGridReadyForUpdate>().Subscribe(_=>{ UpdateLevelSelectionGridFilter(_); }).DisposeWith(this);
        }
        
        protected virtual void OnLevelSelectionUIShownHandler(FlipCube.LevelSelectionUIShown data) {
        }
        
        protected void OnLevelSelectionUIShownFilter(FlipCube.LevelSelectionUIShown data) {
            this.OnLevelSelectionUIShownHandler(data);
        }
        
        protected virtual void SkipChanged(LevelSelectionUI data, LevelSelectionUI group, PropertyChangedEvent<System.Int32> value) {
        }
        
        protected void SkipChangedFilter(LevelSelectionUI data, PropertyChangedEvent<System.Int32> value) {
            var GroupLevelSelectionUI = LevelSelectionUIManager[data.EntityId];
            if (GroupLevelSelectionUI == null) {
                return;
            }
            if (!GroupLevelSelectionUI.Enabled) {
                return;
            }
            this.SkipChanged(data, GroupLevelSelectionUI, value);
        }
        
        protected virtual void OnLevelSelectionUIHidingHandler(FlipCube.LevelSelectionUIHiding data) {
        }
        
        protected void OnLevelSelectionUIHidingFilter(FlipCube.LevelSelectionUIHiding data) {
            this.OnLevelSelectionUIHidingHandler(data);
        }
        
        protected virtual void LevelIndexChanged(LevelSelectionUIItem data, LevelSelectionUIItem group, PropertyChangedEvent<System.Int32> value) {
        }
        
        protected void LevelIndexChangedFilter(LevelSelectionUIItem data, PropertyChangedEvent<System.Int32> value) {
            var GroupLevelSelectionUIItem = LevelSelectionUIItemManager[data.EntityId];
            if (GroupLevelSelectionUIItem == null) {
                return;
            }
            if (!GroupLevelSelectionUIItem.Enabled) {
                return;
            }
            this.LevelIndexChanged(data, GroupLevelSelectionUIItem, value);
        }
        
        protected virtual void HiddenChanged(LevelSelectionUI data, LevelSelectionUI group, PropertyChangedEvent<System.Boolean> value) {
            var handler = new HiddenChanged();
            handler.System = this;
            handler.Event = data;
            handler.Group = group;
            handler.OldValue = value.PreviousValue;
            handler.NewValue = value.CurrentValue;
            StartCoroutine(handler.Execute());
        }
        
        protected void HiddenChangedFilter(LevelSelectionUI data, PropertyChangedEvent<System.Boolean> value) {
            var GroupLevelSelectionUI = LevelSelectionUIManager[data.EntityId];
            if (GroupLevelSelectionUI == null) {
                return;
            }
            if (!GroupLevelSelectionUI.Enabled) {
                return;
            }
            this.HiddenChanged(data, GroupLevelSelectionUI, value);
        }
        
        protected virtual void UpdateLevelSelectionGridHandler(FlipCube.LevelSelectionGridReadyForUpdate data) {
        }
        
        protected void UpdateLevelSelectionGridFilter(FlipCube.LevelSelectionGridReadyForUpdate data) {
            this.UpdateLevelSelectionGridHandler(data);
        }
    }
    
    [uFrame.Attributes.uFrameIdentifier("4e0e6ed9-2181-40c1-aa62-bd0e6b71fc19")]
    public partial class LevelSelectionUISystem : LevelSelectionUISystemBase {
        
        private static LevelSelectionUISystem _Instance;
        
        public LevelSelectionUISystem() {
            Instance = this;
        }
        
        public static LevelSelectionUISystem Instance {
            get {
                return _Instance;
            }
            set {
                _Instance = value;
            }
        }
    }
}
