// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace FlipCube {
    using FlipCube;
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.Kernel;
    using UniRx;
    using UnityEngine;
    
    
    public partial class LevelManagementSystemBase : uFrame.ECS.EcsSystem {
        
        private IEcsComponentManagerOf<Intro> _IntroManager;
        
        private IEcsComponentManagerOf<LevelSceneData> _LevelSceneDataManager;
        
        private IEcsComponentManagerOf<RunningLevel> _RunningLevelManager;
        
        private IEcsComponentManagerOf<LevelData> _LevelDataManager;
        
        private IEcsComponentManagerOf<UIScene> _UISceneManager;
        
        public IEcsComponentManagerOf<Intro> IntroManager {
            get {
                return _IntroManager;
            }
            set {
                _IntroManager = value;
            }
        }
        
        public IEcsComponentManagerOf<LevelSceneData> LevelSceneDataManager {
            get {
                return _LevelSceneDataManager;
            }
            set {
                _LevelSceneDataManager = value;
            }
        }
        
        public IEcsComponentManagerOf<RunningLevel> RunningLevelManager {
            get {
                return _RunningLevelManager;
            }
            set {
                _RunningLevelManager = value;
            }
        }
        
        public IEcsComponentManagerOf<LevelData> LevelDataManager {
            get {
                return _LevelDataManager;
            }
            set {
                _LevelDataManager = value;
            }
        }
        
        public IEcsComponentManagerOf<UIScene> UISceneManager {
            get {
                return _UISceneManager;
            }
            set {
                _UISceneManager = value;
            }
        }
        
        public override void Setup() {
            base.Setup();
            IntroManager = ComponentSystem.RegisterComponent<Intro>(2);
            LevelSceneDataManager = ComponentSystem.RegisterGroup<LevelSceneDataGroup,LevelSceneData>();
            RunningLevelManager = ComponentSystem.RegisterGroup<RunningLevelGroup,RunningLevel>();
            LevelDataManager = ComponentSystem.RegisterComponent<LevelData>(38);
            UISceneManager = ComponentSystem.RegisterComponent<UIScene>(41);
            LevelSceneDataManager.CreatedObservable.Subscribe(LevelSceneDataCreatedFilter).DisposeWith(this);
            RunningLevelManager.CreatedObservable.Subscribe(LevelStartedFilter).DisposeWith(this);
            this.OnEvent<FlipCube.LoadLevel>().Subscribe(_=>{ LevelManagementSystemLoadLevelFilter(_); }).DisposeWith(this);
            RunningLevelManager.RemovedObservable.Subscribe(_=>RunningLevelComponentDestroyed(_,_)).DisposeWith(this);
            this.OnEvent<FlipCube.UnloadAllLevels>().Subscribe(_=>{ LevelManagementSystemUnloadAllLevelsFilter(_); }).DisposeWith(this);
        }
        
        protected virtual void LevelSceneDataCreated(LevelSceneData data, LevelSceneData group) {
        }
        
        protected void LevelSceneDataCreatedFilter(LevelSceneData data) {
            var GroupItem = LevelSceneDataManager[data.EntityId];
            if (GroupItem == null) {
                return;
            }
            if (!GroupItem.Enabled) {
                return;
            }
            this.LevelSceneDataCreated(data, GroupItem);
        }
        
        protected virtual void LevelStarted(RunningLevel data, RunningLevel group) {
        }
        
        protected void LevelStartedFilter(RunningLevel data) {
            var GroupItem = RunningLevelManager[data.EntityId];
            if (GroupItem == null) {
                return;
            }
            if (!GroupItem.Enabled) {
                return;
            }
            this.LevelStarted(data, GroupItem);
        }
        
        protected virtual void LevelManagementSystemLoadLevelHandler(FlipCube.LoadLevel data, LevelData level) {
        }
        
        protected void LevelManagementSystemLoadLevelFilter(FlipCube.LoadLevel data) {
            var LevelLevelData = LevelDataManager[data.Level];
            if (LevelLevelData == null) {
                return;
            }
            if (!LevelLevelData.Enabled) {
                return;
            }
            this.LevelManagementSystemLoadLevelHandler(data, LevelLevelData);
        }
        
        protected virtual void RunningLevelComponentDestroyed(RunningLevel data, RunningLevel group) {
        }
        
        protected void RunningLevelComponentDestroyedFilter(RunningLevel data) {
            var GroupItem = RunningLevelManager[data.EntityId];
            if (GroupItem == null) {
                return;
            }
            if (!GroupItem.Enabled) {
                return;
            }
            this.RunningLevelComponentDestroyed(data, GroupItem);
        }
        
        protected virtual void LevelManagementSystemUnloadAllLevelsHandler(FlipCube.UnloadAllLevels data) {
        }
        
        protected void LevelManagementSystemUnloadAllLevelsFilter(FlipCube.UnloadAllLevels data) {
            this.LevelManagementSystemUnloadAllLevelsHandler(data);
        }
    }
    
    [uFrame.Attributes.uFrameIdentifier("cb99a24a-5702-4984-b147-63e83040489e")]
    public partial class LevelManagementSystem : LevelManagementSystemBase {
        
        private static LevelManagementSystem _Instance;
        
        [UnityEngine.SerializeField()]
        private List<SceneData> _LevelDependencies;
        
        public LevelManagementSystem() {
            Instance = this;
        }
        
        public static LevelManagementSystem Instance {
            get {
                return _Instance;
            }
            set {
                _Instance = value;
            }
        }
        
        public List<SceneData> LevelDependencies {
            get {
                return _LevelDependencies;
            }
            set {
                _LevelDependencies = value;
            }
        }
    }
}
