// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace FlipCube {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using FlipCube;
    using uFrame.Kernel;
    using uFrame.ECS;
    using UniRx;
    
    
    public partial class LevelManagementSystemBase : uFrame.ECS.EcsSystem {
        
        private IEcsComponentManagerOf<Intro> _IntroManager;
        
        private IEcsComponentManagerOf<RunningLevel> _RunningLevelManager;
        
        private IEcsComponentManagerOf<LevelScene> _LevelSceneManager;
        
        private IEcsComponentManagerOf<UIScene> _UISceneManager;
        
        private IEcsComponentManagerOf<ZoneData> _ZoneDataManager;
        
        private IEcsComponentManagerOf<LevelData> _LevelDataManager;
        
        public IEcsComponentManagerOf<Intro> IntroManager {
            get {
                return _IntroManager;
            }
            set {
                _IntroManager = value;
            }
        }
        
        public IEcsComponentManagerOf<RunningLevel> RunningLevelManager {
            get {
                return _RunningLevelManager;
            }
            set {
                _RunningLevelManager = value;
            }
        }
        
        public IEcsComponentManagerOf<LevelScene> LevelSceneManager {
            get {
                return _LevelSceneManager;
            }
            set {
                _LevelSceneManager = value;
            }
        }
        
        public IEcsComponentManagerOf<UIScene> UISceneManager {
            get {
                return _UISceneManager;
            }
            set {
                _UISceneManager = value;
            }
        }
        
        public IEcsComponentManagerOf<ZoneData> ZoneDataManager {
            get {
                return _ZoneDataManager;
            }
            set {
                _ZoneDataManager = value;
            }
        }
        
        public IEcsComponentManagerOf<LevelData> LevelDataManager {
            get {
                return _LevelDataManager;
            }
            set {
                _LevelDataManager = value;
            }
        }
        
        public override void Setup() {
            base.Setup();
            IntroManager = ComponentSystem.RegisterComponent<Intro>(2);
            RunningLevelManager = ComponentSystem.RegisterGroup<RunningLevelGroup,RunningLevel>();
            LevelSceneManager = ComponentSystem.RegisterComponent<LevelScene>(40);
            UISceneManager = ComponentSystem.RegisterComponent<UIScene>(41);
            ZoneDataManager = ComponentSystem.RegisterComponent<ZoneData>(1);
            LevelDataManager = ComponentSystem.RegisterComponent<LevelData>(38);
            LevelSceneManager.CreatedObservable.Subscribe(OnLevelSceneLoadedFilter).DisposeWith(this);
            this.OnEvent<FlipCube.LoadDependencyScenes>().Subscribe(_=>{ OnLoadDepsFilter(_); }).DisposeWith(this);
            RunningLevelManager.CreatedObservable.Subscribe(OnLevelLoadedFilter).DisposeWith(this);
        }
        
        protected virtual void OnLevelSceneLoaded(LevelScene data, LevelScene group) {
        }
        
        protected void OnLevelSceneLoadedFilter(LevelScene data) {
            var GroupLevelScene = LevelSceneManager[data.EntityId];
            if (GroupLevelScene == null) {
                return;
            }
            if (!GroupLevelScene.Enabled) {
                return;
            }
            this.OnLevelSceneLoaded(data, GroupLevelScene);
        }
        
        protected virtual void OnLoadDepsHandler(FlipCube.LoadDependencyScenes data) {
        }
        
        protected void OnLoadDepsFilter(FlipCube.LoadDependencyScenes data) {
            this.OnLoadDepsHandler(data);
        }
        
        protected virtual void OnLevelLoaded(RunningLevel data, RunningLevel group) {
        }
        
        protected void OnLevelLoadedFilter(RunningLevel data) {
            var GroupItem = RunningLevelManager[data.EntityId];
            if (GroupItem == null) {
                return;
            }
            if (!GroupItem.Enabled) {
                return;
            }
            this.OnLevelLoaded(data, GroupItem);
        }
    }
    
    [uFrame.Attributes.uFrameIdentifier("cb99a24a-5702-4984-b147-63e83040489e")]
    public partial class LevelManagementSystem : LevelManagementSystemBase {
        
        private static LevelManagementSystem _Instance;
        
        public LevelManagementSystem() {
            Instance = this;
        }
        
        public static LevelManagementSystem Instance {
            get {
                return _Instance;
            }
            set {
                _Instance = value;
            }
        }
    }
}
