// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace FlipCube {
    using FlipCube;
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.Kernel;
    using UniRx;
    using UnityEngine;
    
    
    public partial class MainMenuUISystemBase : uFrame.ECS.EcsSystem {
        
        private IEcsComponentManagerOf<MainMenuWidget> _MainMenuWidgetManager;
        
        private IEcsComponentManagerOf<MainMenuUI> _MainMenuUIManager;
        
        public IEcsComponentManagerOf<MainMenuWidget> MainMenuWidgetManager {
            get {
                return _MainMenuWidgetManager;
            }
            set {
                _MainMenuWidgetManager = value;
            }
        }
        
        public IEcsComponentManagerOf<MainMenuUI> MainMenuUIManager {
            get {
                return _MainMenuUIManager;
            }
            set {
                _MainMenuUIManager = value;
            }
        }
        
        public override void Setup() {
            base.Setup();
            MainMenuWidgetManager = ComponentSystem.RegisterGroup<MainMenuWidgetGroup,MainMenuWidget>();
            MainMenuUIManager = ComponentSystem.RegisterComponent<MainMenuUI>(90);
            MainMenuWidgetManager.CreatedObservable.Subscribe(MainMenuWidgetCreatedFilter).DisposeWith(this);
        }
        
        protected virtual void MainMenuWidgetCreated(MainMenuWidget data, MainMenuWidget group) {
        }
        
        protected void MainMenuWidgetCreatedFilter(MainMenuWidget data) {
            var GroupItem = MainMenuWidgetManager[data.EntityId];
            if (GroupItem == null) {
                return;
            }
            if (!GroupItem.Enabled) {
                return;
            }
            this.MainMenuWidgetCreated(data, GroupItem);
        }
    }
    
    [uFrame.Attributes.uFrameIdentifier("da3ad502-112f-4b6a-b47f-ae9d23639f82")]
    public partial class MainMenuUISystem : MainMenuUISystemBase {
        
        private static MainMenuUISystem _Instance;
        
        public MainMenuUISystem() {
            Instance = this;
        }
        
        public static MainMenuUISystem Instance {
            get {
                return _Instance;
            }
            set {
                _Instance = value;
            }
        }
    }
}
