// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace FlipCube {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.Kernel;
    using uFrame.ECS;
    
    
    [uFrame.Attributes.uFrameIdentifier("a99a8a88-981c-4efe-b82c-87092772b650")]
    public partial class MiscUISystemLoader : uFrame.Kernel.SystemLoader {
        
        public override void Load() {
            this.AddSystem<MiscUISystem>();
        }
    }
}
