// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace FlipCube {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.Kernel;
    
    
    #region 
static
    public class MiscUIModuleExtensions {
        
        #region 
static
        public uFrame.ECS.IEcsComponentManagerOf<LoadingScreen> LoadingScreenManager(this uFrame.ECS.IEcsSystem system) {
            return system.ComponentSystem.RegisterComponent<LoadingScreen>();
        }
        #endregion
        
        #region 
static
        public uFrame.ECS.IEcsComponentManagerOf<BackgroundTaskIndicator> BackgroundTaskIndicatorManager(this uFrame.ECS.IEcsSystem system) {
            return system.ComponentSystem.RegisterComponent<BackgroundTaskIndicator>();
        }
        #endregion
        
        #region 
static
        public List<LoadingScreen> LoadingScreenComponents(this uFrame.ECS.IEcsSystem system) {
            return system.ComponentSystem.RegisterComponent<LoadingScreen>().Components;
        }
        #endregion
        
        #region 
static
        public List<BackgroundTaskIndicator> BackgroundTaskIndicatorComponents(this uFrame.ECS.IEcsSystem system) {
            return system.ComponentSystem.RegisterComponent<BackgroundTaskIndicator>().Components;
        }
        #endregion
    }
    #endregion
}
