// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace FlipCube {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.Kernel;
    using UniRx;
    using uFrame.ECS;
    
    
    public partial class PlateSystemBase : uFrame.ECS.EcsSystem {
        
        private IEcsComponentManagerOf<Plate> _PlateManager;
        
        public IEcsComponentManagerOf<Plate> PlateManager {
            get {
                return _PlateManager;
            }
            set {
                _PlateManager = value;
            }
        }
        
        public override void Setup() {
            base.Setup();
            PlateManager = ComponentSystem.RegisterComponent<Plate>(27);
        }
    }
    
    [uFrame.Attributes.uFrameIdentifier("9211152d-1874-402a-8c6f-c7089f091056")]
    public partial class PlateSystem : PlateSystemBase {
        
        private static PlateSystem _Instance;
        
        public PlateSystem() {
            Instance = this;
        }
        
        public static PlateSystem Instance {
            get {
                return _Instance;
            }
            set {
                _Instance = value;
            }
        }
    }
}
