// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace FlipCube {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using FlipCube;
    using uFrame.Kernel;
    using uFrame.ECS;
    using UniRx;
    
    
    public partial class ZoneManagementSystemBase : uFrame.ECS.EcsSystem {
        
        private IEcsComponentManagerOf<Intro> _IntroManager;
        
        private IEcsComponentManagerOf<ZoneData> _ZoneDataManager;
        
        public IEcsComponentManagerOf<Intro> IntroManager {
            get {
                return _IntroManager;
            }
            set {
                _IntroManager = value;
            }
        }
        
        public IEcsComponentManagerOf<ZoneData> ZoneDataManager {
            get {
                return _ZoneDataManager;
            }
            set {
                _ZoneDataManager = value;
            }
        }
        
        public override void Setup() {
            base.Setup();
            IntroManager = ComponentSystem.RegisterComponent<Intro>(2);
            ZoneDataManager = ComponentSystem.RegisterComponent<ZoneData>(1);
        }
    }
    
    [uFrame.Attributes.uFrameIdentifier("cb99a24a-5702-4984-b147-63e83040489e")]
    public partial class ZoneManagementSystem : ZoneManagementSystemBase {
        
        private static ZoneManagementSystem _Instance;
        
        public ZoneManagementSystem() {
            Instance = this;
        }
        
        public static ZoneManagementSystem Instance {
            get {
                return _Instance;
            }
            set {
                _Instance = value;
            }
        }
    }
}
