// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using Invert.ECS;


public class PlayerStatBase : Invert.ECS.Unity.UnityComponent {
    
    [UnityEngine.SerializeField()]
    private String _Key;
    
    [UnityEngine.SerializeField()]
    private Int32 _Value;
    
    public virtual String Key {
        get {
            return _Key;
        }
        set {
            _Key = value;
        }
    }
    
    public virtual Int32 Value {
        get {
            return _Value;
        }
        set {
            _Value = value;
        }
    }
}

[UnityEngine.AddComponentMenu("PlayerData/PlayerStat")]
public partial class PlayerStat {
}
