// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using Invert.ECS;


public enum RollerState {
    
    StandingUp,
    
    LayingAcross,
    
    LayingForward,
}

public enum CubeMoveDirection {
    
    Left,
    
    Right,
    
    Forward,
    
    Backwards,
}

public enum SwitchPlatePivot {
    
    Bottom,
    
    Top,
    
    Left,
    
    Right,
}

public enum CubeSystemEvents {
    
    RollBegin,
    
    RollComplete,
    
    Reset,
    
    MoveTo,
}

public enum CubeInputSystemEvents {
    
    Selected,
    
    L,
    
    F,
    
    R,
    
    B,
}

public enum CubeGravitySystemEvents {
    
    OnFall,
    
    RollCompletedStandingUp,
}

public enum CameraSystemEvents {
}

public enum PlateSystemEvents {
    
    CubeEntered,
    
    CubeLeft,
    
    GoalPlateHit,
    
    SwitchPlateHit,
    
    CubeEnteredStandingUp,
}

public enum TeliporterSystemEvents {
}

public enum SwitchPlateSystemEvents {
    
    PlateActivatedOn,
    
    PlateActivatedOff,
}

public enum ShiftingPlateEvents {
}

public enum GoalPlateSystemEvents {
}

public enum LevelSystemEvents {
    
    LevelComplete,
    
    LevelQuit,
    
    RestartLevel,
    
    LevelFailed,
    
    NextLevel,
}

public enum FlipCubeGameSystemEvents {
    
    GameOver,
}

public enum FlipCubeNotificationsEvents {
}

public enum SpecialFXSystemEvents {
}

public enum FlipCubeSoundSystemEvents {
}

public enum NotificationSystemEvents {
    
    Display,
}

public enum FlipCubeUISystemEvents {
}

public enum HUDSystemEvents {
}

public enum XPSystemEvents {
}

public enum PlayerSystemEvents {
    
    PlayerLoaded,
}
