// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using Invert.ECS;


public class ZoneEventDataBase : object {
    
    private Int32 _ZoneId;
    
    private String _SceneName;
    
    public Int32 ZoneId {
        get {
            return _ZoneId;
        }
        set {
            _ZoneId = value;
        }
    }
    
    public String SceneName {
        get {
            return _SceneName;
        }
        set {
            _SceneName = value;
        }
    }
}
