// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using Invert.ECS;


public class ZoneSystemBase : UnitySystem {
    
    private ComponentManager<Zone> _ZoneManager;
    
    private ComponentManager<ZoneScene> _ZoneSceneManager;
    
    public ComponentManager<Zone> ZoneManager {
        get {
            return _ZoneManager;
        }
        set {
            _ZoneManager = value;
        }
    }
    
    public ComponentManager<ZoneScene> ZoneSceneManager {
        get {
            return _ZoneSceneManager;
        }
        set {
            _ZoneSceneManager = value;
        }
    }
    
    public override void Initialize(Invert.ECS.IGame game) {
        base.Initialize(game);
        ZoneManager = game.ComponentSystem.RegisterComponent<Zone>();
        ZoneSceneManager = game.ComponentSystem.RegisterComponent<ZoneScene>();
        game.EventManager.ListenFor( FrameworkEvents.ComponentCreated, ComponentCreated );
    }
    
    protected virtual void ComponentCreated(Invert.ECS.IEvent e) {
    }
    
    public virtual void SignalEnterZone(ZoneEventData data) {
        Game.EventManager.SignalEvent(new EventData(ZoneSystemEvents.EnterZone,data));
    }
    
    public virtual void SignalEnteredZone(ZoneEventData data) {
        Game.EventManager.SignalEvent(new EventData(ZoneSystemEvents.EnteredZone,data));
    }
    
    public static void SignalEnterZone(IGame game, ZoneEventData data) {
        game.EventManager.SignalEvent(new EventData(ZoneSystemEvents.EnterZone,data));
    }
    
    public static void SignalEnteredZone(IGame game, ZoneEventData data) {
        game.EventManager.SignalEvent(new EventData(ZoneSystemEvents.EnteredZone,data));
    }
}

public enum ZoneSystemEvents {
    
    EnterZone,
    
    EnteredZone,
}
