// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace FlipCube {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine.UI;
    using UnityEngine;
    using uFrame.ECS;
    using Invert.Json;
    using UniRx;
    
    
    [uFrame.Attributes.ComponentId(30)]
    [uFrame.Attributes.uFrameIdentifier("91bd34f2-eba6-4909-b584-67d42a245119")]
    public partial class BackgroundTaskIndicator : uFrame.ECS.EcsComponent, uFrame.ECS.IBlackBoardComponent {
        
        [UnityEngine.SerializeField()]
        private Text _MessageText;
        
        [UnityEngine.SerializeField()]
        private GameObject _UIContainer;
        
        [UnityEngine.SerializeField()]
        private String _Message;
        
        [UnityEngine.SerializeField()]
        private Boolean _IsRunning;
        
        private Subject<PropertyChangedEvent<Text>> _MessageTextObservable;
        
        private PropertyChangedEvent<Text> _MessageTextEvent;
        
        private Subject<PropertyChangedEvent<GameObject>> _UIContainerObservable;
        
        private PropertyChangedEvent<GameObject> _UIContainerEvent;
        
        private Subject<PropertyChangedEvent<String>> _MessageObservable;
        
        private PropertyChangedEvent<String> _MessageEvent;
        
        private Subject<PropertyChangedEvent<Boolean>> _IsRunningObservable;
        
        private PropertyChangedEvent<Boolean> _IsRunningEvent;
        
        public override int ComponentId {
            get {
                return 30;
            }
        }
        
        public IObservable<PropertyChangedEvent<Text>> MessageTextObservable {
            get {
                return _MessageTextObservable ?? (_MessageTextObservable = new Subject<PropertyChangedEvent<Text>>());
            }
        }
        
        public IObservable<PropertyChangedEvent<GameObject>> UIContainerObservable {
            get {
                return _UIContainerObservable ?? (_UIContainerObservable = new Subject<PropertyChangedEvent<GameObject>>());
            }
        }
        
        public IObservable<PropertyChangedEvent<String>> MessageObservable {
            get {
                return _MessageObservable ?? (_MessageObservable = new Subject<PropertyChangedEvent<String>>());
            }
        }
        
        public IObservable<PropertyChangedEvent<Boolean>> IsRunningObservable {
            get {
                return _IsRunningObservable ?? (_IsRunningObservable = new Subject<PropertyChangedEvent<Boolean>>());
            }
        }
        
        public Text MessageText {
            get {
                return _MessageText;
            }
            set {
                SetMessageText(value);
            }
        }
        
        public GameObject UIContainer {
            get {
                return _UIContainer;
            }
            set {
                SetUIContainer(value);
            }
        }
        
        public String Message {
            get {
                return _Message;
            }
            set {
                SetMessage(value);
            }
        }
        
        public Boolean IsRunning {
            get {
                return _IsRunning;
            }
            set {
                SetIsRunning(value);
            }
        }
        
        public virtual void SetMessageText(Text value) {
            SetProperty(ref _MessageText, value, ref _MessageTextEvent, _MessageTextObservable);
        }
        
        public virtual void SetUIContainer(GameObject value) {
            SetProperty(ref _UIContainer, value, ref _UIContainerEvent, _UIContainerObservable);
        }
        
        public virtual void SetMessage(String value) {
            SetProperty(ref _Message, value, ref _MessageEvent, _MessageObservable);
        }
        
        public virtual void SetIsRunning(Boolean value) {
            SetProperty(ref _IsRunning, value, ref _IsRunningEvent, _IsRunningObservable);
        }
    }
}
