// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace FlipCube {
    using Invert.Json;
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using UniRx;
    using UnityEngine;
    
    
    [uFrame.Attributes.ComponentId(47)]
    [uFrame.Attributes.uFrameIdentifier("09898d79-91e4-46c3-86f7-3bd374bbf965")]
    public partial class DissolvePlate : uFrame.ECS.EcsComponent {
        
        [UnityEngine.SerializeField()]
        private Boolean _IsDissolved;
        
        private Subject<PropertyChangedEvent<Boolean>> _IsDissolvedObservable;
        
        private PropertyChangedEvent<Boolean> _IsDissolvedEvent;
        
        public override int ComponentId {
            get {
                return 47;
            }
        }
        
        public IObservable<PropertyChangedEvent<Boolean>> IsDissolvedObservable {
            get {
                return _IsDissolvedObservable ?? (_IsDissolvedObservable = new Subject<PropertyChangedEvent<Boolean>>());
            }
        }
        
        public Boolean IsDissolved {
            get {
                return _IsDissolved;
            }
            set {
                SetIsDissolved(value);
            }
        }
        
        public virtual void SetIsDissolved(Boolean value) {
            SetProperty(ref _IsDissolved, value, ref _IsDissolvedEvent, _IsDissolvedObservable);
        }
    }
}
