// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace FlipCube {
    using FlipCube;
    using Invert.Json;
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using UniRx;
    using UnityEngine;
    
    
    [uFrame.Attributes.ComponentId(88)]
    [uFrame.Attributes.uFrameIdentifier("6e87cb22-0061-4664-8b64-038b6ae6fedb")]
    public partial class GameUI : uFrame.ECS.EcsComponent, uFrame.ECS.IBlackBoardComponent {
        
        [UnityEngine.SerializeField()]
        private GeneralGameUIState _State;
        
        private Subject<PropertyChangedEvent<GeneralGameUIState>> _StateObservable;
        
        private PropertyChangedEvent<GeneralGameUIState> _StateEvent;
        
        public override int ComponentId {
            get {
                return 88;
            }
        }
        
        public IObservable<PropertyChangedEvent<GeneralGameUIState>> StateObservable {
            get {
                return _StateObservable ?? (_StateObservable = new Subject<PropertyChangedEvent<GeneralGameUIState>>());
            }
        }
        
        public GeneralGameUIState State {
            get {
                return _State;
            }
            set {
                SetState(value);
            }
        }
        
        public virtual void SetState(GeneralGameUIState value) {
            SetProperty(ref _State, value, ref _StateEvent, _StateObservable);
        }
    }
}
