// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace FlipCube {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using FlipCube;
    using uFrame.ECS;
    using UniRx;
    using Invert.Json;
    using UnityEngine;
    
    
    [uFrame.Attributes.ComponentId(36)]
    [uFrame.Attributes.uFrameIdentifier("537fbd98-c66a-4c65-a408-699c1e57ec4d")]
    public partial class GameUI : uFrame.ECS.EcsComponent {
        
        [UnityEngine.SerializeField()]
        private Animator _MainMenuAnimator;
        
        [UnityEngine.SerializeField()]
        private GeneralGameUIState _GeneralState;
        
        private Subject<PropertyChangedEvent<Animator>> _MainMenuAnimatorObservable;
        
        private PropertyChangedEvent<Animator> _MainMenuAnimatorEvent;
        
        private Subject<PropertyChangedEvent<GeneralGameUIState>> _GeneralStateObservable;
        
        private PropertyChangedEvent<GeneralGameUIState> _GeneralStateEvent;
        
        public override int ComponentId {
            get {
                return 36;
            }
        }
        
        public IObservable<PropertyChangedEvent<Animator>> MainMenuAnimatorObservable {
            get {
                return _MainMenuAnimatorObservable ?? (_MainMenuAnimatorObservable = new Subject<PropertyChangedEvent<Animator>>());
            }
        }
        
        public IObservable<PropertyChangedEvent<GeneralGameUIState>> GeneralStateObservable {
            get {
                return _GeneralStateObservable ?? (_GeneralStateObservable = new Subject<PropertyChangedEvent<GeneralGameUIState>>());
            }
        }
        
        public Animator MainMenuAnimator {
            get {
                return _MainMenuAnimator;
            }
            set {
                SetMainMenuAnimator(value);
            }
        }
        
        public GeneralGameUIState GeneralState {
            get {
                return _GeneralState;
            }
            set {
                SetGeneralState(value);
            }
        }
        
        public virtual void SetMainMenuAnimator(Animator value) {
            SetProperty(ref _MainMenuAnimator, value, ref _MainMenuAnimatorEvent, _MainMenuAnimatorObservable);
        }
        
        public virtual void SetGeneralState(GeneralGameUIState value) {
            SetProperty(ref _GeneralState, value, ref _GeneralStateEvent, _GeneralStateObservable);
        }
    }
}
