// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace FlipCube {
    using Invert.Json;
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using UniRx;
    using UnityEngine;
    
    
    [uFrame.Attributes.ComponentId(96)]
    [uFrame.Attributes.uFrameIdentifier("c7c52f37-ef44-4a00-9f66-cbfcf58b28be")]
    public partial class GameDependency : uFrame.ECS.EcsComponent {
        
        public override int ComponentId {
            get {
                return 96;
            }
        }
    }
}
