// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace FlipCube {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using FlipCube;
    using Invert.Json;
    using UniRx;
    using UnityEngine;
    using uFrame.ECS;
    
    
    [uFrame.Attributes.ComponentId(2)]
    [uFrame.Attributes.uFrameIdentifier("847abbcb-779d-4ebf-94b6-2d298d4cc72a")]
    public partial class Intro : uFrame.ECS.EcsComponent {
        
        [UnityEngine.SerializeField()]
        private CanvasGroup _Logo;
        
        private Subject<PropertyChangedEvent<CanvasGroup>> _LogoObservable;
        
        private PropertyChangedEvent<CanvasGroup> _LogoEvent;
        
        public override int ComponentId {
            get {
                return 2;
            }
        }
        
        public IObservable<PropertyChangedEvent<CanvasGroup>> LogoObservable {
            get {
                return _LogoObservable ?? (_LogoObservable = new Subject<PropertyChangedEvent<CanvasGroup>>());
            }
        }
        
        public CanvasGroup Logo {
            get {
                return _Logo;
            }
            set {
                SetLogo(value);
            }
        }
        
        public virtual void SetLogo(CanvasGroup value) {
            SetProperty(ref _Logo, value, ref _LogoEvent, _LogoObservable);
        }
    }
}
