// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace FlipCube {
    using Invert.Json;
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using Invert.Json;
    using UnityEngine;
    using UniRx;
    
    
    [uFrame.Attributes.ComponentId(39)]
    [uFrame.Attributes.uFrameIdentifier("848358c0-a2f1-4a7a-b681-3cdbf85a25ad")]
    public partial class KeyboardPlayerInput : uFrame.ECS.EcsComponent {
        
        public override int ComponentId {
            get {
                return 39;
            }
        }
    }
}
