// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace FlipCube {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using FlipCube;
    using Invert.Json;
    using uFrame.ECS;
    using UniRx;
    using UnityEngine;
    
    
    [uFrame.Attributes.ComponentId(44)]
    [uFrame.Attributes.uFrameIdentifier("55170ed3-4a31-4c51-ba69-04ebac8f7ab5")]
    public partial class LevelSelectionUI : uFrame.ECS.EcsComponent, uFrame.ECS.IBlackBoardComponent {
        
        [UnityEngine.SerializeField()]
        private Animator _Animator;
        
        [UnityEngine.SerializeField()]
        private Boolean _IsDirty;
        
        [UnityEngine.SerializeField()]
        private Int32 _Page;
        
        [UnityEngine.SerializeField()]
        private Int32 _Skip;
        
        [UnityEngine.SerializeField()]
        private Int32 _Limit;
        
        [UnityEngine.SerializeField()]
        private LevelSelectionUIItem[] _UIItems;
        
        private ReactiveCollection<LevelSelectionUIItem> _UIItemsReactive;
        
        private Subject<PropertyChangedEvent<Animator>> _AnimatorObservable;
        
        private PropertyChangedEvent<Animator> _AnimatorEvent;
        
        private Subject<PropertyChangedEvent<Boolean>> _IsDirtyObservable;
        
        private PropertyChangedEvent<Boolean> _IsDirtyEvent;
        
        private Subject<PropertyChangedEvent<Int32>> _PageObservable;
        
        private PropertyChangedEvent<Int32> _PageEvent;
        
        private Subject<PropertyChangedEvent<Int32>> _SkipObservable;
        
        private PropertyChangedEvent<Int32> _SkipEvent;
        
        private Subject<PropertyChangedEvent<Int32>> _LimitObservable;
        
        private PropertyChangedEvent<Int32> _LimitEvent;
        
        public override int ComponentId {
            get {
                return 44;
            }
        }
        
        public IObservable<PropertyChangedEvent<Animator>> AnimatorObservable {
            get {
                return _AnimatorObservable ?? (_AnimatorObservable = new Subject<PropertyChangedEvent<Animator>>());
            }
        }
        
        public IObservable<PropertyChangedEvent<Boolean>> IsDirtyObservable {
            get {
                return _IsDirtyObservable ?? (_IsDirtyObservable = new Subject<PropertyChangedEvent<Boolean>>());
            }
        }
        
        public IObservable<PropertyChangedEvent<Int32>> PageObservable {
            get {
                return _PageObservable ?? (_PageObservable = new Subject<PropertyChangedEvent<Int32>>());
            }
        }
        
        public IObservable<PropertyChangedEvent<Int32>> SkipObservable {
            get {
                return _SkipObservable ?? (_SkipObservable = new Subject<PropertyChangedEvent<Int32>>());
            }
        }
        
        public IObservable<PropertyChangedEvent<Int32>> LimitObservable {
            get {
                return _LimitObservable ?? (_LimitObservable = new Subject<PropertyChangedEvent<Int32>>());
            }
        }
        
        public Animator Animator {
            get {
                return _Animator;
            }
            set {
                SetAnimator(value);
            }
        }
        
        public Boolean IsDirty {
            get {
                return _IsDirty;
            }
            set {
                SetIsDirty(value);
            }
        }
        
        public Int32 Page {
            get {
                return _Page;
            }
            set {
                SetPage(value);
            }
        }
        
        public Int32 Skip {
            get {
                return _Skip;
            }
            set {
                SetSkip(value);
            }
        }
        
        public Int32 Limit {
            get {
                return _Limit;
            }
            set {
                SetLimit(value);
            }
        }
        
        public ReactiveCollection<LevelSelectionUIItem> UIItems {
            get {
                if (_UIItemsReactive == null) {
                    _UIItemsReactive = new ReactiveCollection<LevelSelectionUIItem>(_UIItems ?? new LevelSelectionUIItem[] { });
                }
                return _UIItemsReactive;
            }
        }
        
        public virtual void SetAnimator(Animator value) {
            SetProperty(ref _Animator, value, ref _AnimatorEvent, _AnimatorObservable);
        }
        
        public virtual void SetIsDirty(Boolean value) {
            SetProperty(ref _IsDirty, value, ref _IsDirtyEvent, _IsDirtyObservable);
        }
        
        public virtual void SetPage(Int32 value) {
            SetProperty(ref _Page, value, ref _PageEvent, _PageObservable);
        }
        
        public virtual void SetSkip(Int32 value) {
            SetProperty(ref _Skip, value, ref _SkipEvent, _SkipObservable);
        }
        
        public virtual void SetLimit(Int32 value) {
            SetProperty(ref _Limit, value, ref _LimitEvent, _LimitObservable);
        }
    }
}
