// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace FlipCube {
    using Invert.Json;
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using UniRx;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    [uFrame.Attributes.ComponentId(78)]
    [uFrame.Attributes.uFrameIdentifier("08ba657c-ec42-41e3-b77a-8abcb64c2d6e")]
    public partial class LevelSelectionUI : uFrame.ECS.EcsComponent {
        
        [UnityEngine.SerializeField()]
        private Button _BackButton;
        
        [UnityEngine.SerializeField()]
        private Button _NextButton;
        
        private Subject<PropertyChangedEvent<Button>> _BackButtonObservable;
        
        private PropertyChangedEvent<Button> _BackButtonEvent;
        
        private Subject<PropertyChangedEvent<Button>> _NextButtonObservable;
        
        private PropertyChangedEvent<Button> _NextButtonEvent;
        
        public override int ComponentId {
            get {
                return 78;
            }
        }
        
        public IObservable<PropertyChangedEvent<Button>> BackButtonObservable {
            get {
                return _BackButtonObservable ?? (_BackButtonObservable = new Subject<PropertyChangedEvent<Button>>());
            }
        }
        
        public IObservable<PropertyChangedEvent<Button>> NextButtonObservable {
            get {
                return _NextButtonObservable ?? (_NextButtonObservable = new Subject<PropertyChangedEvent<Button>>());
            }
        }
        
        public Button BackButton {
            get {
                return _BackButton;
            }
            set {
                SetBackButton(value);
            }
        }
        
        public Button NextButton {
            get {
                return _NextButton;
            }
            set {
                SetNextButton(value);
            }
        }
        
        public virtual void SetBackButton(Button value) {
            SetProperty(ref _BackButton, value, ref _BackButtonEvent, _BackButtonObservable);
        }
        
        public virtual void SetNextButton(Button value) {
            SetProperty(ref _NextButton, value, ref _NextButtonEvent, _NextButtonObservable);
        }
    }
}
