// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace FlipCube {
    using Invert.Json;
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using UniRx;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    [uFrame.Attributes.ComponentId(74)]
    [uFrame.Attributes.uFrameIdentifier("541879fa-dc60-4f3a-8eeb-390a5eceacaa")]
    public partial class LoadingPanel : uFrame.ECS.EcsComponent {
        
        [UnityEngine.SerializeField()]
        private String _Message;
        
        [UnityEngine.SerializeField()]
        private Text _MessageText;
        
        private Subject<PropertyChangedEvent<String>> _MessageObservable;
        
        private PropertyChangedEvent<String> _MessageEvent;
        
        private Subject<PropertyChangedEvent<Text>> _MessageTextObservable;
        
        private PropertyChangedEvent<Text> _MessageTextEvent;
        
        public override int ComponentId {
            get {
                return 74;
            }
        }
        
        public IObservable<PropertyChangedEvent<String>> MessageObservable {
            get {
                return _MessageObservable ?? (_MessageObservable = new Subject<PropertyChangedEvent<String>>());
            }
        }
        
        public IObservable<PropertyChangedEvent<Text>> MessageTextObservable {
            get {
                return _MessageTextObservable ?? (_MessageTextObservable = new Subject<PropertyChangedEvent<Text>>());
            }
        }
        
        public String Message {
            get {
                return _Message;
            }
            set {
                SetMessage(value);
            }
        }
        
        public Text MessageText {
            get {
                return _MessageText;
            }
            set {
                SetMessageText(value);
            }
        }
        
        public virtual void SetMessage(String value) {
            SetProperty(ref _Message, value, ref _MessageEvent, _MessageObservable);
        }
        
        public virtual void SetMessageText(Text value) {
            SetProperty(ref _MessageText, value, ref _MessageTextEvent, _MessageTextObservable);
        }
    }
}
