// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace FlipCube {
    using Invert.Json;
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using UniRx;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    [uFrame.Attributes.ComponentId(29)]
    [uFrame.Attributes.uFrameIdentifier("5012518a-c67e-4aa8-91d9-e82fb38a0635")]
    public partial class LoadingScreen : uFrame.ECS.EcsComponent, uFrame.ECS.IBlackBoardComponent {
        
        [UnityEngine.SerializeField()]
        private Text _MessageText;
        
        [UnityEngine.SerializeField()]
        private Boolean _IsLoading;
        
        [UnityEngine.SerializeField()]
        private GameObject _UIContainer;
        
        [UnityEngine.SerializeField()]
        private String _Message;
        
        private Subject<PropertyChangedEvent<Text>> _MessageTextObservable;
        
        private PropertyChangedEvent<Text> _MessageTextEvent;
        
        private Subject<PropertyChangedEvent<Boolean>> _IsLoadingObservable;
        
        private PropertyChangedEvent<Boolean> _IsLoadingEvent;
        
        private Subject<PropertyChangedEvent<GameObject>> _UIContainerObservable;
        
        private PropertyChangedEvent<GameObject> _UIContainerEvent;
        
        private Subject<PropertyChangedEvent<String>> _MessageObservable;
        
        private PropertyChangedEvent<String> _MessageEvent;
        
        public override int ComponentId {
            get {
                return 29;
            }
        }
        
        public IObservable<PropertyChangedEvent<Text>> MessageTextObservable {
            get {
                return _MessageTextObservable ?? (_MessageTextObservable = new Subject<PropertyChangedEvent<Text>>());
            }
        }
        
        public IObservable<PropertyChangedEvent<Boolean>> IsLoadingObservable {
            get {
                return _IsLoadingObservable ?? (_IsLoadingObservable = new Subject<PropertyChangedEvent<Boolean>>());
            }
        }
        
        public IObservable<PropertyChangedEvent<GameObject>> UIContainerObservable {
            get {
                return _UIContainerObservable ?? (_UIContainerObservable = new Subject<PropertyChangedEvent<GameObject>>());
            }
        }
        
        public IObservable<PropertyChangedEvent<String>> MessageObservable {
            get {
                return _MessageObservable ?? (_MessageObservable = new Subject<PropertyChangedEvent<String>>());
            }
        }
        
        public Text MessageText {
            get {
                return _MessageText;
            }
            set {
                SetMessageText(value);
            }
        }
        
        public Boolean IsLoading {
            get {
                return _IsLoading;
            }
            set {
                SetIsLoading(value);
            }
        }
        
        public GameObject UIContainer {
            get {
                return _UIContainer;
            }
            set {
                SetUIContainer(value);
            }
        }
        
        public String Message {
            get {
                return _Message;
            }
            set {
                SetMessage(value);
            }
        }
        
        public virtual void SetMessageText(Text value) {
            SetProperty(ref _MessageText, value, ref _MessageTextEvent, _MessageTextObservable);
        }
        
        public virtual void SetIsLoading(Boolean value) {
            SetProperty(ref _IsLoading, value, ref _IsLoadingEvent, _IsLoadingObservable);
        }
        
        public virtual void SetUIContainer(GameObject value) {
            SetProperty(ref _UIContainer, value, ref _UIContainerEvent, _UIContainerObservable);
        }
        
        public virtual void SetMessage(String value) {
            SetProperty(ref _Message, value, ref _MessageEvent, _MessageObservable);
        }
    }
}
