// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace FlipCube {
    using Invert.Json;
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using UniRx;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    [uFrame.Attributes.ComponentId(90)]
    [uFrame.Attributes.uFrameIdentifier("2455ad7b-22aa-42b8-88aa-1afc5f41e213")]
    public partial class MainMenuUI : uFrame.ECS.EcsComponent {
        
        [UnityEngine.SerializeField()]
        private Button _PlayButton;
        
        [UnityEngine.SerializeField()]
        private Button _QuitButton;
        
        [UnityEngine.SerializeField()]
        private Button _LeaderBoardButton;
        
        private Subject<PropertyChangedEvent<Button>> _PlayButtonObservable;
        
        private PropertyChangedEvent<Button> _PlayButtonEvent;
        
        private Subject<PropertyChangedEvent<Button>> _QuitButtonObservable;
        
        private PropertyChangedEvent<Button> _QuitButtonEvent;
        
        private Subject<PropertyChangedEvent<Button>> _LeaderBoardButtonObservable;
        
        private PropertyChangedEvent<Button> _LeaderBoardButtonEvent;
        
        public override int ComponentId {
            get {
                return 90;
            }
        }
        
        public IObservable<PropertyChangedEvent<Button>> PlayButtonObservable {
            get {
                return _PlayButtonObservable ?? (_PlayButtonObservable = new Subject<PropertyChangedEvent<Button>>());
            }
        }
        
        public IObservable<PropertyChangedEvent<Button>> QuitButtonObservable {
            get {
                return _QuitButtonObservable ?? (_QuitButtonObservable = new Subject<PropertyChangedEvent<Button>>());
            }
        }
        
        public IObservable<PropertyChangedEvent<Button>> LeaderBoardButtonObservable {
            get {
                return _LeaderBoardButtonObservable ?? (_LeaderBoardButtonObservable = new Subject<PropertyChangedEvent<Button>>());
            }
        }
        
        public Button PlayButton {
            get {
                return _PlayButton;
            }
            set {
                SetPlayButton(value);
            }
        }
        
        public Button QuitButton {
            get {
                return _QuitButton;
            }
            set {
                SetQuitButton(value);
            }
        }
        
        public Button LeaderBoardButton {
            get {
                return _LeaderBoardButton;
            }
            set {
                SetLeaderBoardButton(value);
            }
        }
        
        public virtual void SetPlayButton(Button value) {
            SetProperty(ref _PlayButton, value, ref _PlayButtonEvent, _PlayButtonObservable);
        }
        
        public virtual void SetQuitButton(Button value) {
            SetProperty(ref _QuitButton, value, ref _QuitButtonEvent, _QuitButtonObservable);
        }
        
        public virtual void SetLeaderBoardButton(Button value) {
            SetProperty(ref _LeaderBoardButton, value, ref _LeaderBoardButtonEvent, _LeaderBoardButtonObservable);
        }
    }
}
