// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace FlipCube {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using Invert.Json;
    using UnityEngine;
    using UniRx;
    
    
    [uFrame.Attributes.ComponentId(26)]
    [uFrame.Attributes.uFrameIdentifier("887aeca0-2fea-4a0b-a821-91f06cc79317")]
    public partial class Player : uFrame.ECS.EcsComponent {
        
        public override int ComponentId {
            get {
                return 26;
            }
        }
    }
}
