// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace FlipCube {
    using Invert.Json;
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using UniRx;
    using UnityEngine;
    
    
    [uFrame.Attributes.ComponentId(61)]
    [uFrame.Attributes.uFrameIdentifier("8fcf3891-352b-4510-9add-5421a93df78b")]
    public partial class Singular : uFrame.ECS.EcsComponent {
        
        public override int ComponentId {
            get {
                return 61;
            }
        }
    }
}
