// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace FlipCube {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using UniRx;
    using Invert.Json;
    using UnityEngine;
    
    
    [uFrame.Attributes.ComponentId(46)]
    [uFrame.Attributes.uFrameIdentifier("48999917-4f8c-4541-bfba-d12baf40d336")]
    public partial class SwitchPlateTrigger : uFrame.ECS.EcsComponent {
        
        [UnityEngine.SerializeField()]
        private Boolean _On;
        
        [UnityEngine.SerializeField()]
        private Int32 _GroupNumber;
        
        private Subject<PropertyChangedEvent<Boolean>> _OnObservable;
        
        private PropertyChangedEvent<Boolean> _OnEvent;
        
        private Subject<PropertyChangedEvent<Int32>> _GroupNumberObservable;
        
        private PropertyChangedEvent<Int32> _GroupNumberEvent;
        
        public override int ComponentId {
            get {
                return 46;
            }
        }
        
        public IObservable<PropertyChangedEvent<Boolean>> OnObservable {
            get {
                return _OnObservable ?? (_OnObservable = new Subject<PropertyChangedEvent<Boolean>>());
            }
        }
        
        public IObservable<PropertyChangedEvent<Int32>> GroupNumberObservable {
            get {
                return _GroupNumberObservable ?? (_GroupNumberObservable = new Subject<PropertyChangedEvent<Int32>>());
            }
        }
        
        public Boolean On {
            get {
                return _On;
            }
            set {
                SetOn(value);
            }
        }
        
        public Int32 GroupNumber {
            get {
                return _GroupNumber;
            }
            set {
                SetGroupNumber(value);
            }
        }
        
        public virtual void SetOn(Boolean value) {
            SetProperty(ref _On, value, ref _OnEvent, _OnObservable);
        }
        
        public virtual void SetGroupNumber(Int32 value) {
            SetProperty(ref _GroupNumber, value, ref _GroupNumberEvent, _GroupNumberObservable);
        }
    }
}
