// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace FlipCube {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using Invert.Json;
    using UnityEngine;
    using UniRx;
    
    
    [uFrame.Attributes.ComponentId(41)]
    [uFrame.Attributes.uFrameIdentifier("27a52365-baa2-4fa4-b359-d1a05a2db406")]
    public partial class UIScene : uFrame.ECS.EcsComponent {
        
        public override int ComponentId {
            get {
                return 41;
            }
        }
    }
}
